version: "3.7"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "10"
      max-size: "100m"

services:

  nginx-web:
    image: nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx-web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/data/nginx/certs:/etc/nginx/certs:ro
      - /var/data/nginx/vhost.d:/etc/nginx/vhost.d
      - /var/data/nginx/html:/usr/share/nginx/html
      - /var/data/nginx/conf.d:/etc/nginx/conf.d
      # - /var/data/nginx/htpasswd:/etc/nginx/htpasswd:ro
    networks:
      - default
      - outside
    <<: *logging

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx-web -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: always
    environment:
      SSL_POLICY: Mozilla-Intermediate
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/data/nginx/certs:/etc/nginx/certs:ro
      - /var/data/nginx/vhost.d:/etc/nginx/vhost.d
      - /var/data/nginx/html:/usr/share/nginx/html
      - /var/data/nginx/conf.d:/etc/nginx/conf.d
      # - /var/data/nginx/htpasswd:/etc/nginx/htpasswd:ro
      - /var/config/nginx-gen/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    networks:
      - default
      - outside
    <<: *logging

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/data/nginx/certs:/etc/nginx/certs:rw
      - /var/data/nginx/vhost.d:/etc/nginx/vhost.d
      - /var/data/nginx/html:/usr/share/nginx/html
      - /var/data/nginx/conf.d:/etc/nginx/conf.d
      - /var/data/nginx/acme:/etc/acme.sh:rw
    environment:
      DEFAULT_EMAIL: $WEB_ADMIN_EMAIL
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen
      NGINX_PROXY_CONTAINER: nginx-web
    networks:
      - default
      - outside
    <<: *logging

  eth1:
    image: ethereum/client-go:stable
    restart: always
    hostname: eth1
    # https://geth.ethereum.org/docs/interface/command-line-options
    command:
      - --datadir=/data/geth
      - --datadir.ancient=/extra-data/geth
      - --maxpeers=100
      - --cache=10240
      - --nousb
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.vhosts=eth1
      - --rpcapi=eth,net,web3
      - --metrics
      - --pprof
      - --pprof.addr=0.0.0.0
      # network
      - ${ETH1_NETWORK_FLAG}
    ports:
      # eth json rpc
      - 8545
      # metrics for prometheus
      - 6060
      # public p2p
      - 30303:30303/tcp
      - 30303:30303/udp
    volumes:
      - eth1_data:/data
      - /mnt/extra-data:/extra-data
    networks:
      - default
      - outside
    <<: *logging

  beacon:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
    restart: always
    hostname: beacon
    # https://docs.prylabs.network/docs/prysm-usage/parameters/
    command:
      - --accept-terms-of-use
      - --datadir=/extra-data/beacon
      # Connectivity settings
      - --rpc-host=0.0.0.0
      - --monitoring-host=0.0.0.0
      # disable scan of local network
      - --p2p-denylist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,100.64.0.0/10,169.254.0.0/16
      - --p2p-tcp-port=13000
      - --p2p-max-peers=100
      # Connection to eth1
      - --http-web3provider=http://eth1:8545
      - --historical-slasher-node
      - --block-batch-limit=512
      # https://github.com/attestantio/vouch/issues/6
      - --rpc-max-page-size=100000
      - --grpc-max-msg-size=268435456
      # network
      - ${ETH2_NETWORK_FLAG}
    ports:
      # json-http api
      - 3500
      # grpc
      - 4000
      # metrics for prometheus
      - 8080
      # public p2p
      - 13000:13000/tcp
      - 12000:12000/udp
    volumes:
      - /mnt/extra-data:/extra-data
    networks:
      - default
      - outside
    <<: *logging

  validator:
    image: gcr.io/prysmaticlabs/prysm/validator:stable
    restart: on-failure
    hostname: validator
    # https://docs.prylabs.network/docs/prysm-usage/parameters/
    command:
      - --accept-terms-of-use
      # Connectivity
      - --beacon-rpc-provider=beacon:4000
      - --monitoring-host=0.0.0.0
      # Validator database, accounts & key management
      - --datadir=/data/db
      - --wallet-dir=/data/wallets
      - --wallet-password-file=/data/passwords/wallet-password
      # network
      - ${ETH2_NETWORK_FLAG}
    ports:
      # metrics for prometheus
      - 8081
    volumes:
      - validator_data:/data
    <<: *logging

  slasher:
    image: gcr.io/prysmaticlabs/prysm/slasher:stable
    restart: always
    hostname: slasher
    # https://docs.prylabs.network/docs/prysm-usage/parameters/
    command:
      - --accept-terms-of-use
      - --datadir=/data
      # Connectivity
      - --beacon-rpc-provider=beacon:4000
      - --monitoring-host=0.0.0.0
      - --monitoring-port=8680
      - --rpc-host=0.0.0.0
      # Enables historical attestation detection for the slasher
      - --enable-historical-detection
      # network
      - ${ETH2_NETWORK_FLAG}
    ports:
      # grpc
      - 4002
      # metrics for prometheus
      - 8680
    volumes:
      - slasher_data:/data
    <<: *logging

  node-exporter:
    image: prom/node-exporter
    restart: always
    hostname: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /mnt/extra-data:/mnt/extra-data:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      # metrics for prometheus
      - 9100

  prometheus:
    image: prom/prometheus:v2.19.0
    user: root # https://github.com/prometheus/prometheus/issues/5976
    restart: on-failure
    hostname: prometheus
    command: --storage.tsdb.retention.time=31d --config.file=/etc/prometheus/prometheus.yaml
    ports:
      # !non-authenticating! dashboard ui
      - 9090
    volumes:
      - /var/config/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    <<: *logging

  grafana:
    image: grafana/grafana:7.3.4
    user: root
    restart: on-failure
    hostname: grafana
    ports:
      # authenticating dashboard ui
      - 3000
    volumes:
      - /var/config/grafana:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      LETSENCRYPT_HOST: $WEB_DASHBOARD_DOMAIN
      VIRTUAL_HOST: $WEB_DASHBOARD_DOMAIN
      VIRTUAL_PORT: 3000
    <<: *logging

volumes:
  prometheus_data: {}
  grafana_data: {}
  validator_data: {}
  slasher_data: {}
  eth1_data: {}

networks:
  default:
  outside: