{
 "title": "Geth Syncing",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "tx_pool_counters",
    "label": "TxPoolCounters",
    "query": "{job=\"geth\"}"
   },
   { "name": "job", "query": "geth" },
   {
    "name": "quantile",
    "query": "0.5, 0.75, 0.95, 0.99, 0.999, 0.9999"
   }
  ]
 },
 "panels": [
  { "title": "State Import", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "State Import Rate 30m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(eth_downloader_states_in[30m])",
     "legendFormat": "state import"
    }
   ]
  },
  {
   "title": "State Import Rate 1m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(eth_downloader_states_in[1m])",
     "legendFormat": "state import"
    }
   ]
  },
  {
   "title": "Disk activity 30m",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(system_disk_readbytes[30m])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(system_disk_writebytes[30m])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Disk activity 1m",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(system_disk_readbytes[1m])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(system_disk_writebytes[1m])",
     "legendFormat": "write"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "ioawait",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "system_cpu_syswait", "legendFormat": "iowait" }
   ]
  },
  {
   "title": "system",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "system_cpu_sysload", "legendFormat": "system" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "rate(system_memory_allocs[1m])", "legendFormat": "alloc" },
    { "expr": "system_memory_used", "legendFormat": "used" },
    { "expr": "system_memory_held", "legendFormat": "held" }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "rate(p2p_ingress[1m])", "legendFormat": "ingress" },
    { "expr": "rate(p2p_egress[1m])", "legendFormat": "egress" }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "p2p_peers", "legendFormat": "peers" },
    { "expr": "rate(p2p_dials[1m])", "legendFormat": "dials" },
    { "expr": "rate(p2p_serves[1m])", "legendFormat": "serves" }
   ]
  },
  { "title": "Blockchain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Latest header",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "chain_head_header" }
   ]
  },
  {
   "title": "Chain head",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "chain_head_header", "legendFormat": "header" },
    { "expr": "chain_head_receipt", "legendFormat": "receipt" },
    { "expr": "chain_head_block", "legendFormat": "block" }
   ]
  },
  {
   "title": "Chain rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(chain_head_header[1m])", "legendFormat": "header" },
    { "expr": "rate(chain_head_receipt[1m])", "legendFormat": "receipt" },
    { "expr": "rate(chain_head_block[1m])", "legendFormat": "block" }
   ]
  },
  {
   "title": "Latest receipt",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "chain_head_receipt" }
   ]
  },
  {
   "title": "Latest block",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "chain_head_block" }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Data rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(eth_db_chaindata_disk_read[1m])",
     "legendFormat": "leveldb read"
    },
    {
     "expr": "rate(eth_db_chaindata_disk_write[1m])",
     "legendFormat": "leveldb write"
    },
    {
     "expr": "rate(eth_db_chaindata_ancient_read[1m])",
     "legendFormat": "ancient read"
    },
    {
     "expr": "rate(eth_db_chaindata_ancient_write[1m])",
     "legendFormat": "ancient write"
    }
   ]
  },
  {
   "title": "Session totals",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "eth_db_chaindata_disk_read", "legendFormat": "leveldb read" },
    { "expr": "eth_db_chaindata_disk_write", "legendFormat": "leveldb write" },
    { "expr": "eth_db_chaindata_ancient_read", "legendFormat": "ancient read" },
    { "expr": "eth_db_chaindata_ancient_write", "legendFormat": "ancient write" }
   ]
  },
  {
   "title": "Storage size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "eth_db_chaindata_disk_size", "legendFormat": "leveldb" },
    { "expr": "eth_db_chaindata_ancient_size", "legendFormat": "ancient" }
   ]
  }
 ]
}