global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'geth'
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: ['eth1:6060']

  - job_name: 'beacon node'
    static_configs:
      - targets: ['beacon:8080']

  - job_name: 'validator'
    static_configs:
      - targets: ['validator:8081']

  - job_name: 'slasher'
    static_configs:
      - targets: ['slasher:8680']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']